### ISSUE TITLE
Dubbele solids lagen

### ISSUE THREAD

**Issue by rajv1970** [jeroenVerdonschot/pdok-converter-issues#1]
Hoi Jeroen,
Een probleempje dat ik nog zag was dat bij het importeren van de hatches lagen, de lagen er dubbel in komen te staan. 1 keer normaal, en 1 keer met een extra streepje voor en achter de oorsponkelijke laagnaam.
![image](https://user-images.githubusercontent.com/66624013/84029122-2f2cb580-a992-11ea-8157-ff6c1bc4bc76.png)

**Comment by jeroenVerdonschot** [comment]
ah. dat is gek. er staan ook gekke streepjes achter. Zou je me de DXF kunnen mailen?

**Comment by jeroenVerdonschot** [comment]
probleem is opgelost
